Based on the provided {data} answer the {question} question.

Context:
This is data on how many people are currently standing in line at the cantina.
The best time to get to the location is when number of people is at its lowest.

Provide very precise answer to the question - only time and date is required.

If question is not related to date or time, tell that question is not supported.

The response should be in the following format: The best time to get to cantine is at dd-MM-yyyy HH:mm.
